<x-layouts.app>
    <x-show
        :title="$armor->name"
        :item="$armor"
        :partial="'partials._item'"
        :index="'item'"
        :itemClassType="'armor'"
    ></x-show>
</x-layouts.app>
