<x-layouts.app>
    <x-show
        :title="$recipe->name"
        :entity="$recipe"
        :partial="'partials._recipe'"
        :index="'recipe'"
        :entity_class_type="'recipe'"
    ></x-show>
</x-layouts.app>
