<x-layouts.app>
    <x-show
        :title="$item->name"
        :entity="$item"
        :partial="'partials._item'"
        :index="'item'"
        :entityClassType="'item'"
    ></x-show>
</x-layouts.app>
